function showValues() {
    swal({
        title: "Aquí encontrarás el significado de los valores de tú tabla",
        text: `    "P_0A2", #Población de 0 a 2 años de la AGEB urbana (personas)
        "P_3YMAS", #Población de 3 años y más de la AGEB urbana (personas)
        "P_3YMAS_F", #Población femenina de 3 años y más de la AGEB urbana (personas)
        "P_3YMAS_M", #Población masculina de 3 años y más de la AGEB urbana (personas)
        "P_5YMAS", #Población de 5 años y más de la AGEB urbana (personas)
        "P_5YMAS_F", #Población femenina de 5 años y más de la AGEB urbana (personas)
        "P_5YMAS_M", #Población masculina de 5 años y más de la AGEB urbana (personas)
        "P_12YMAS", #Población de 12 años y más de la AGEB urbana (personas)
        "P_12YMAS_F", #Población femenina de 12 años y más de la AGEB urbana (personas)
        "P_12YMAS_M", #Población masculina de 12 años y más de la AGEB urbana (personas)
        "P_15YMAS", #Población de 15 años y más de la AGEB urbana (personas)
        "P_15YMAS_F", #Población femenina de 15 años y más de la AGEB urbana (personas)
        "P_15YMAS_M", #Población masculina de 15 años y más de la AGEB urbana (personas)
        "P_18YMAS", #Población de 18 años y más de la AGEB urbana (personas)
        "P_18YMAS_F", #Población femenina de 18 años y más de la AGEB urbana (personas)
        "P_18YMAS_M", #Población masculina de 18 años y más de la AGEB urbana (personas)
        "P_3A5", #Población de 3 a 5 años de la AGEB urbana (personas)
        "P_3A5_F", #Población femenina de 3 a 5 años de la AGEB urbana (personas)
        "P_3A5_M", #Población masculina de 3 a 5 años de la AGEB urbana (personas)
        "P_6A11", #Población de 6 a 11 años de la AGEB urbana (personas)
        "P_6A11_F", #Población femenina de 6 a 11 años de la AGEB urbana (personas)
        "P_6A11_M", #Población masculina de 6 a 11 años de la AGEB urbana (personas)
        "P_8A14_F", #Población femenina de 8 a 14 años de la AGEB urbana (personas)
        "P_8A14_M", #Población masculina de 8 a 14 años de la AGEB urbana (personas)
        "P_12A14", #Población de 12 a 14 años de la AGEB urbana (personas)
        "P_12A14_F", #Población femenina de 12 a 14 años de la AGEB urbana (personas)
        "P_12A14_M", #Población masculina de 12 a 14 años de la AGEB urbana (personas)
        "P_15A17", #Población de 15 a 17 años de la AGEB urbana (personas)
        "P_15A17_F", #Población femenina de 15 a 17 años de la AGEB urbana (personas)
        "P_15A17_M", #Población masculina de 15 a 17 años de la AGEB urbana (personas)
        "P_18A24", #Población de 18 a 24 años de la AGEB urbana (personas)
        "P_18A24_F", #Población femenina de 18 a 24 años de la AGEB urbana (personas)
        "P_18A24_M", #Población masculina de 18 a 24 años de la AGEB urbana (personas)
        "P_15A49_F", #Población femenina de 15 a 49 años de la AGEB urbana (personas)
        "P_60YMAS", #Población de 60 años y más de la AGEB urbana (personas)
        "P_60YMAS_F", #Población femenina de 60 años y más de la AGEB urbana (personas)
        "P_60YMAS_M", #Población masculina de 60 años y más de la AGEB urbana (personas)
        "POB0_14", #Población de 0 a 14 años de la AGEB urbana (personas)
        "POB15_64", #Población de 15 a 64 años de la AGEB urbana (personas)
        "POB65_MAS", #Población de 65 años y más de la AGEB urbana (personas)
        "P3A5_NOA",  #Población de 3 a 5 años de la AGEB urbana que no asiste a la escuela (personas)
        "P3A5_NOA_F", #Población femenina de 3 a 5 años de la AGEB urbana que no asiste a la escuela (personas)
        "P3A5_NOA_M", #Población masculina de 3 a 5 años de la AGEB urbana que no asiste a la escuela (personas)
        "P6A11_NOA", #Población de 6 a 11 años de la AGEB urbana que no asiste a la escuela (personas)
        "P6A11_NOAF", #Población femenina de 6 a 11 años de la AGEB urbana que no asiste a la escuela (personas)
        "P6A11_NOAM", #Población masculina de 6 a 11 años de la AGEB urbana que no asiste a la escuela (personas)
        "P12A14NOA", #Población de 12 a 14 años de la AGEB urbana que no asiste a la escuela (personas)
        "P12A14NOAF", #Población femenina de 12 a 14 años de la AGEB urbana que no asiste a la escuela (personas)
        "P12A14NOAM", #Población masculina de 12 a 14 años de la AGEB urbana que no asiste a la escuela (personas)
        "P15A17A", #Población de 15 a 17 años de la AGEB urbana que asiste a la escuela (personas)
        "P15A17A_F", #Población femenina de 15 a 17 años de la AGEB urbana que asiste a la escuela (personas)
        "P15A17A_M", #Población masculina de 15 a 17 años de la AGEB urbana que asiste a la escuela (personas)
        "P18A24A", #Población de 18 a 24 años de la AGEB urbana que asiste a la escuela (personas)
        "P18A24A_F", #Población femenina de 18 a 24 años de la AGEB urbana que asiste a la escuela (personas)
        "P18A24A_M", #Población masculina de 18 a 24 años de la AGEB urbana que asiste a la escuela (personas)
        "P8A14AN", #Población de 8 a 14 años de la AGEB urbana que es analfabeta (personas)
        "P8A14AN_F", #Población femenina de 8 a 14 años de la AGEB urbana que es analfabeta (personas)
        "P8A14AN_M", #Población masculina de 8 a 14 años de la AGEB urbana que es analfabeta (personas)
        "P15YM_AN", #Población de 15 años y más de la AGEB urbana que es analfabeta (personas)
        "P15YM_AN_F", #Población femenina de 15 años y más de la AGEB urbana que es analfabeta (personas)
        "P15YM_AN_M", #Población masculina de 15 años y más de la AGEB urbana que es analfabeta (personas)
        "P15YM_SE", #Población de 15 años y más de la AGEB urbana sin escolaridad (personas)
        "P15YM_SE_F", #Población femenina de 15 años y más de la AGEB urbana sin escolaridad (personas)
        "P15YM_SE_M", #Población masculina de 15 años y más de la AGEB urbana sin escolaridad (personas)
        "P15PRI_IN", #Población de 15 años y más de la AGEB urbana que tiene primaria incompleta (personas)
        "P15PRI_INF", #Población femenina de 15 años y más de la AGEB urbana que tiene primaria incompleta (personas)
        "P15PRI_INM", #Población masculina de 15 años y más de la AGEB urbana que tiene primaria incompleta (personas)
        "P15PRI_CO", #Población de 15 años y más de la AGEB urbana que tiene primaria completa (personas)
        "P15PRI_COF", #Población femenina de 15 años y más de la AGEB urbana que tiene primaria completa (personas)
        "P15PRI_COM", #Población masculina de 15 años y más de la AGEB urbana que tiene primaria completa (personas)
        "P15SEC_IN", #Población de 15 años y más de la AGEB urbana que tiene secundaria incompleta (personas)
        "P15SEC_INF", #Población femenina de 15 años y más de la AGEB urbana que tiene secundaria incompleta (personas)
        "P15SEC_INM", #Población masculina de 15 años y más de la AGEB urbana que tiene secundaria incompleta (personas)
        "P15SEC_CO", #Población de 15 años y más de la AGEB urbana que tiene secundaria completa (personas)
        "P15SEC_COF", #Población femenina de 15 años y más de la AGEB urbana que tiene secundaria completa (personas)
        "P15SEC_COM", #Población masculina de 15 años y más de la AGEB urbana que tiene secundaria completa (personas)
        "P18YM_PB", #Población de 18 años y más de la AGEB urbana que tiene educación posbásica (personas)
        "P18YM_PB_F", #Población femenina de 18 años y más de la AGEB urbana que tiene educación posbásica (personas)
        "P18YM_PB_M", #Población masculina de 18 años y más de la AGEB urbana que tiene educación posbásica (personas)
        "GRAPROES", #Grado promedio de escolaridad de la AGEB urbana (grados)
        "GRAPROES_F", #Grado promedio de escolaridad de la AGEB urbana de la población femenina (grados)
        "GRAPROES_M", #Grado promedio de escolaridad de la AGEB urbana de la población masculina (grados)
        "PEA", #Población de 12 años y más económicamente activa de la AGEB urbana (personas)
        "PEA_F", #Población femenina de 12 años y más económicamente activa de la AGEB urbana (personas)
        "PEA_M", #Población masculina de 12 años y más económicamente activa de la AGEB urbana (personas)
        "PE_INAC", #Población de 12 años y más económicamente inactiva de la AGEB urbana (personas)
        "PE_INAC_F", #Población femenina de 12 años y más económicamente inactiva de la AGEB urbana (personas)
        "PE_INAC_M", #Población masculina de 12 años y más económicamente inactiva de la AGEB urbana (personas)
        "POCUPADA", #Población ocupada de 12 años y más de la AGEB urbana (personas)
        "POCUPADA_F", #Población ocupada de 12 años y más de la AGEB urbana de la población femenina (personas)
        "POCUPADA_M", #Población ocupada de 12 años y más de la AGEB urbana de la población masculina (personas)
        "PDESOCUP", #Población desocupada de 12 años y más de la AGEB urbana (personas)
        "PDESOCUP_F", #Población desocupada de 12 años y más de la AGEB urbana de la población femenina (personas)
        "PDESOCUP_M", #Población desocupada de 12 años y más de la AGEB urbana de la población masculina (personas)
        "P12YM_SOLT", #Población de 12 años y más de la AGEB urbana soltera o nunca unida (personas)
        "P12YM_CASA", #Población de 12 años y más de la AGEB urbana que vive casada o unida (personas)
        "P12YM_SEPA", #Población de 12 años y más de la AGEB urbana que estuvo casada o unida (personas)
        "PCATOLICA", #Población con religion catolica de 12 años y más de la AGEB urbana (personas)
        "PRO_CRIEVA", #Poblacion con grupo religioso protestante/ cristiano evangélico de 12 años y más de la AGEB urbana (personas)
        "POTRAS_REL", #Poblacion con otras religiones diferentes a las anteriores de la AGEB urbana (personas)
        "PSIN_RELIG" #Poblacion sin religion o sin adscripción religiosa de la AGEB urbana (personas)`,
        button: "OK",
    });
}

document.getElementById("dict").addEventListener("click", function () {
    showValues();
});